{{- $chartname := .Chart.Name -}}
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ $chartname }}
    namespace: {{ .Release.Namespace }}
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ $chartname }}
    minReplicas: {{ .Values.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.autoscaling.maxReplicas }}
    targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
